apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-client
  template:
    metadata:
      labels:
        app: mysql-client
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          command: ["sleep", "3600"]
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: host
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password